### ISSUE TITLE
Potentially redundant code?

### ISSUE THREAD

**Issue by levilovearch** [elicassion/StARformer#2]
Dear developer,

Thanks for sharing your excellent work. I found something interesting in `starformer.py` Line 317
`
if i == 0:
    local_tokens, global_state_tokens, local_att, global_att = blk(local_tokens, global_state_tokens, temporal_emb)
else:
    local_tokens, global_state_tokens, local_att, global_att = blk(local_tokens, global_state_tokens, temporal_emb)
` 
It looks like the if condition is not necessary.

Best regards,
Levi

**Comment by elicassion** [comment]
Hi Levi,

Good catch! That was possibly used when trying to adapt to other variants of starformer, but was removed later. It's not critical and feel free to change it to what you prefer to on your side. I will double-check and update it later.
