### ISSUE TITLE
how to run with DMC

### ISSUE THREAD

**Issue by STAN-32** [elicassion/StARformer#4]
I have downloaded the dmc dataset and provide the correct data_directory.
It seems that dmc share the same create_dataset function with atari case, is it reasonable to load dataset?
Meanwhile, it seems some important args is missed in dmc env with the given instruction
```
python run_star_dmc.py --seed 123 --data_dir_prefix [data_directory] --epochs 10 --seq_len 30 --model_type 'star' --batch_size 64 --domain ball_in_cup --task catch --lr 1e-4
```

The following error occurs
```
    obss, actions, returns, done_idxs, _ = create_dataset(args.num_buffers, args.num_steps, args.game, args.data_dir_prefix, args.trajectories_per_buffer, args)
AttributeError: 'Namespace' object has no attribute 'game'
```

**Comment by STAN-32** [comment]
Even this path is fixed with the appropriate args setting and the final correct datapath is given to the replay_buffer in utils
```
def _load_buffer(self, suffix):
    """Loads a OutOfGraphReplayBuffer replay buffer."""
    try:
      # pytype: disable=attribute-error
      replay_buffer = circular_replay_buffer.OutOfGraphReplayBuffer(
          *self._args, **self._kwargs)
      replay_buffer.load(self._data_dir, suffix)
      tf.logging.info('Loaded replay buffer ckpt {} from {}'.format(
          suffix, self._data_dir))
      # pytype: enable=attribute-error
      return replay_buffer
```

The replay_buffer returned is still None, I just wondering if the pkl files can not be read directly. Since your project is aimed for image, how can we fulfill data reading for pkl files of dmc env?

**Comment by elicassion** [comment]
Hi,

Sorry for the confusion. These lines about dataset are not cleaned up. Please use the latest commit for the right dataset loading (plus your changes for sure).

It will be straightforward for have your own DMC dataset loading. As in [DMC Dataset Class](https://github.com/elicassion/StARformer/blob/main/atari_and_dmc/run_star_dmc.py#L325), it reads dataset file in our customized format. You can freely modify it to match your collected dataset.

Thanks again for catching this bug!
