### ISSUE TITLE
Difference between the two starformer.py files?

### ISSUE THREAD

**Issue by shahaamirbader** [elicassion/StARformer#5]
Hi,

Congratulations for such an awesome work. I being new to DT, was wondering what's the main differences between the two starformer.py files in each environment? And also what is the need to have two different files for each environment. Why not one single straformer.py suffice for both?

**Comment by elicassion** [comment]
Hi @shahaamirbader,

The main difference is input. The `starformer.py` under `atari_and_dmc` deals with image inputs, while the one under `gym` deals with numerial state inputs.

Our paper does not include the results on `gym` environments, but StARformer does work for numerical state inputs and we observed improvements there.

**Comment by shahaamirbader** [comment]
Thanks for clarification. This brings me to my next question. Can your code be used as a code base for other image related inputs for a custom environment?

**Comment by elicassion** [comment]
Sure. Like what we did in `atari_and_dmc/run_star_atari.py` and `atari_and_dmc/run_star_dmc.py`, you will need to modify:

- Environment
- Dataset
- Input & output dimension / space

I think taking a look into those two files will give you enough hints.

**Comment by shahaamirbader** [comment]
thanks a ton. closing this.
